#debug: true

server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: JM Spring Boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Europe/Moscow&useLegacyDatetimeCode=false
    username: root
    password: admin
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
#          База не создается что бы я не делал, никак инициализировать создание jdbc не получатеся, интернет облазил
          charset_name: UTF-8
          import_files: base.sql
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    add-properties: true
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .html
  web:
    locale: ru_RU


logging:
  charset:
    console: UTF-8
